# Generated by Django 3.2.5 on 2021-08-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('id_card', models.TextField(max_length=15, unique=True)),
                ('phone', models.TextField(max_length=15)),
                ('email', models.TextField(max_length=40)),
                ('department', models.TextField(max_length=30)),
                ('supervisor', models.TextField(max_length=30)),
                ('status', models.TextField(default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=40)),
                ('id_number', models.TextField(max_length=40)),
                ('phone_number', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('target_office', models.TextField(max_length=40)),
                ('purpose', models.TextField(max_length=100)),
                ('vehicle_reg', models.TextField(default='None', max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('staff_checkedout', models.TextField(blank=True, max_length=40, null=True)),
                ('status', models.TextField(default='OPEN', max_length=10)),
                ('staff_checkedin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.station')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('staff_checkedout', models.TextField(blank=True, max_length=40, null=True)),
                ('status', models.TextField(default='OPEN', max_length=10)),
                ('staff_checkedin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.station')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, default='Full Name', max_length=40)),
                ('id_number', models.TextField(blank=True, default='ID Number', max_length=15)),
                ('staff_number', models.TextField(blank=True, default='Staff Number', max_length=20)),
                ('staff_phone', models.TextField(blank=True, default='Staff Phone', max_length=15)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.station')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.TextField(max_length=40)),
                ('driver', models.TextField(max_length=70)),
                ('purpose', models.TextField(default='Staff', max_length=30)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('staff_checkedout', models.TextField(blank=True, max_length=40, null=True)),
                ('status', models.TextField(default='OPEN', max_length=10)),
                ('staff_checkedin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.station')),
            ],
        ),
    ]
