# Generated by Django 3.2.5 on 2021-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='purpose',
            field=models.CharField(default='Staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='staff_checkedout',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='Full Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, default='ID Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staff_number',
            field=models.CharField(blank=True, default='Staff Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staff_phone',
            field=models.CharField(blank=True, default='Staff Phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='staff_checkedout',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='staff_checkedout',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='target_office',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vehicle_reg',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
