# Generated by Django 3.2.5 on 2021-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20210807_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='OPEN', max_length=40),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(default='OPEN', max_length=40),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=40),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='OPEN', max_length=40),
        ),
    ]
