# Generated by Django 3.2.5 on 2021-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20210807_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_occupants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_occupants',
            field=models.IntegerField(default=0),
        ),
    ]
