# Generated by Django 3.2.5 on 2021-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20211015_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_occupants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vehicle_occupants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
