# Generated by Django 3.2.5 on 2021-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_visitor_vehicle_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_occupants',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
